# ভূমিকা {.unnumbered}

## নাল অ্যান্ড ভয়েড {#null-and-void}

ইউএসএস ইয়র্কটাউন জাহাজে শূন্যের আঘাতটা টর্পেডোর মতোই হলো।

১৯৯৭ সালের ২১ সেপ্টেম্বর। জাহাজটি ভার্জিনিয়া উপকূল থেকে প্রমোদভ্রমণে বের হয়। শত কোটি ডলারের মিসাইল ক্রুজারটি হঠাৎ কাঁপতে কাঁপতে থেমে যায়। ইয়র্কটাউন জাহাজের সলীল সমাধি ওখানেই।

যুদ্ধজাহাজগুলো বানানোই হয় টর্পেডো বা বিস্ফোরকের আঘাতের প্রতি সহনীয় করে। ইয়র্কটাউন জাহাজকে সব ধরনের অস্ত্র থেকে বাঁচানোর ব্যবস্থা করা হয়েছিল। কিন্তু শূন্য থেকে বাঁচানোর কথা কেউ ভাবেনি। মারাত্মক এক ভুল।

মাত্রই ইয়র্কটাউনের কম্পিউটারে নতুন এক সফটওয়্যার ইন্সটল করা হয়েছে। এটিই নিয়ন্ত্রণ করছে জাহাজের ইঞ্জিন। কিন্তু কোডের মধ্যে যে একটি টাইম বোমা লুকিয়ে আছে তা খেয়াল করেনি। সফটওয়্যার ইন্সটল করার সময় শূন্যটার দিকে প্রকৌশলীদের নজর দেওয়া উচিত ছিল। কিন্তু কী কারণে কে জানে—শূন্যটার দিকে কেউ তাকিয়ে দেখেনি। ফলে সেটি লুকিয়ে থাকল কোডের ভিড়ে। যতক্ষণ না  সফটওয়্যার শূন্যটাকে মেমোরিতে নিয়ে আসল। আর তাতেই সব শেষ।

ইয়র্কটাউনের কম্পিউটার শূন্য দিয়ে ভাগ করার চেষ্টা করেছিল। সাথে সাথে ৮০ হাজার হর্সপাওয়ারের যান অকেজো হয়ে গেল। ইঞ্জিনকে জরুরি নিয়ন্ত্রণ ব্যবস্থায় আনতে প্রায় তিন ঘণ্টা সময় লেগে গিয়েছিল। পরে কোনোরকমে তীরে ভিড়তে সক্ষম হয়। শূন্য থেকে মুক্তি পাওয়া, ইঞ্জিন মেরামত করা ও ইয়র্কটাউনকে পুনরায় সচল করতে লেগে গেল দুই দিন সময়।

অন্য কোনো সংখ্যার দ্বারা এমন ক্ষতি করা সম্ভব নয়। ইয়র্কটাউনে ঘটা কম্পিউটারের ত্রুটি শূন্যের ক্ষমতার খুব ছোট্ট এক নমুনা। বিভিন্ন সংস্কৃতির মানুষ শূন্যের বিরুদ্ধে রুখে দাঁড়িয়েছিল। শূন্যের মুখোমুখি হলে দার্শনিকদের বিদ্যেবুদ্ধি লোপ পেত। কারণ শূন্য অন্য সংখ্যা থেকে একেবারেই আলাদা। অবর্ণনীয় ও অসীমের এক ছোট্ট বহিঃপ্রকাশ। এ কারণেই মানুষ একে ভয় পেয়েছে। ঘৃণা করেছে। নিষিদ্ধ করেছে।

এ বইটা শূন্যের গল্প। প্রাচীনকালে এর জন্মের কথা। প্রাচ্যে এর সাদরে গৃহীত হবার কথা। ইউরোপে স্বীকৃতি পাওয়ার সংগ্রাম। আর আধুনিক পদার্থবিদ্যায় এর নিত্যনতুন হুমকির কথা। এখানে বলা হয়েছে সেইসব পণ্ডিত, মরমিবাদী, বিজ্ঞানী ও পাদ্রীদের কথা যারা এই সংখ্যাটির অর্থ নিয়ে লড়াই করেছেন। প্রত্যেকেই বুঝতে চেয়েছেন। প্রাচ্যের ধারণাগুলো থেকে নিজেদেরকে অপ্রয়োজনীয়ভাবে (কখনও কখনও সহিংস উপায়ে) মুক্ত রাখার পাশ্চ্যাতের একটি ব্যর্থ চেষ্টারও ইতিহাস এটি। এছাড়াও একটি সরল-দর্শন সংখ্যা থেকে সৃষ্ট বিভিন্ন প্যারাডক্সেরও ইতিহাস এটি। বর্তমান শতাব্দীর সেরা বুদ্ধির মানুষগুলোও পেরে উঠছেন না এর সাথে। বৈজ্ঞানিক চিন্তার পুরো অবকাঠামোকে হয়ত এই সংখ্যাটিই পরিষ্কার করবে।

শূন্যের অনেক ক্ষমতার কারণ এটি অসীমের যমজ। এরা সমান এবং বিপরীত। একের মধ্যে দুই। বিভ্রান্তির জন্ম ও কষ্ট দেওয়ার ক্ষেত্রে দুটোরই অবদান সমান। বিজ্ঞান ও ধর্মের বড় বড় প্রশ্নগুলো করা হয় শূন্যতা ও চিরন্ততা নিয়ে। শূন্যতা ও অসীমতা নিয়ে। শূন্য ও অসীম নিয়ে। শূন্য নিয়ে সংঘটিত যুদ্ধ দর্শন, বিজ্ঞান, গণিত ও ধর্মের ভিত্তিতে আলোড়ন তুলেছিল। সব বিপ্লবের পেছনে কাজ করেছে শূন্য। সাথে ছিল অসীম।

প্রাচ্য ও পাশ্চ্যাতের সংঘাতের মূলে ছিল শূন্য। খৃষ্টধর্ম ও বিজ্ঞানের সংগ্রামের কেন্দ্রে ছিল শূন্য। শূন্য পরিণত হলো প্রকৃতির ভাষায়। হয়ে গেল গণিতের সবচেয়ে গুরুত্বপূর্ণ হাতিয়ার। পদার্থবিজ্ঞানের সবচেয়ে ব্যাপক সমস্যাগুলোর সমাধানে মোকাবেলা করতে হয় শূন্যকে। হোক সে ব্ল্যাকহোলের অন্ধকার কেন্দ্র কিংবা বিগ ব্যাংয়ের উজ্জ্বল ঝলক।

কিন্তু ইতিহাসে পাতা বলছে, বাজিমাত সবসময় করেছে শূন্যই। প্রত্যাখ্যান, নির্বাসন সব মোকাবেলা করে শূন্য সবসময় প্রতিপক্ষকে হারিয়ে দিয়েছে। মানুষ কখনোই শূন্যকে দর্শনে অন্তর্ভূক্ত হতে বাধ্য করতে পারেনি। বরং মহাবিশ্ব ও ঈশ্বরের ধারণা পেতে শূন্যের কাছেই যেতে হয়েছে মানুষকে।

