project:
  type: book
  output-dir: "."

output-dir:

book:
  title: "কোয়ান্টাম স্পেস"
  author: "জিম ব্যাগট, আব্দুল্যাহ আদিল মাহমুদ (অনুবাদক)"
  date: "2/1/2026"
  chapters:
    - index.qmd
    - 1-same-law.qmd
    - 10-no-time-like-present.qmd
    - references.qmd
  appendices:
    - about-lqg.qmd

bibliography: references.bib

crossref:
  appendix-title: "পরিশিষ্ট"

format:
  html:
    theme: cosmo




