# লুপ কোয়ান্টাম গ্র্যাভিটিই কি সার্বিক তত্ত্ব?

প্রকৃতির চার বলের মধ্যে মানুষ সবার আগে জানতে ও বুঝতে পারে মহাকর্ষের কথা। তবু এখন পর্যন্ত এ বল সম্পর্কেই মানুষ সবচেয়ে কম জানে। পড়ন্ত আপেল বা গ্রহ-নক্ষত্রের গতি ব্যাখ্যায় আমাদের তত্ত্বগুলো যথেষ্ট সফল। কিন্তু কেউ জানে না, অতিপারমাণবিক কণার ক্ষুদ্র জগতে মহাকর্ষের ভূমিকা কেমন। সে জন্যই বিজ্ঞানীদের চাওয়া এমন এক তত্ত্ব, যা ছায়াপথ থেকে কোয়ার্ক কণা পর্যন্ত বড়-ছোট সবকিছু ব্যাখ্যা করতে পারবে।

অনেক বড় চাওয়া। মহাবিশ্বের অন্যতম জটিল ও কষ্টসাধ্য কাজ। তাই তো অনুসন্ধান শুরুর পর আটটি দশক পার হয়ে গেলেও এখনো মেলেনি দেখা। এখনো তাই মহাবিশ্বের বড় ও ছোট জগতের জন্য আলাদা সূত্র। বড় কাঠামোয় ভালো কাজ করে মহাকর্ষ। যার সবচেয়ে আধুনিক ব্যাখ্যা দেয় আইনস্টাইনের সার্বিক আপেক্ষিকতা তত্ত্ব। এ তত্ত্বে বস্তুর ভর আশপাশের স্থান-কালকে বাঁকিয়ে দেয়। তাকেই আমরা দেখি মহাকর্ষ হিসেবে।

এযাবৎকালের সব পরীক্ষা সফলভাবে উতরে গেছে তত্ত্বটি৷ অতিপারমাণবিক কণার ক্ষুদ্রজগতে আবার কাজ করে কোয়ান্টাম তত্ত্ব। এ তত্ত্ব কাজ করে তিনটি বল নিয়ে: বিদ্যুৎ–চুম্বকীয় বল এবং দুর্বল ও সবল নিউক্লীয় বল। বল তিনটির ব্যাখ্যায় কাজ করে কণাপদার্থবিদ্যার স্ট্যান্ডার্ড মডেল। এসব বলে অংশ নেওয়া কণাদের আচরণও ব্যাখ্যা করে মডেলটি। নিজ নিজ জগতে তত্ত্ব দুটি সফল হলেও অন্যের জগতে অসহায়।

অন্যদিকে বিশাল গ্রহ, নক্ষত্রও পরমাণু দিয়ে তৈরি। এই কণাদের ভাঙা বা জোড়া লাগা থেকে পাওয়া যায় আকর্ষণ ও বিকর্ষণ। চুম্বকের বিপরীত মেরু আকৃষ্ট হয়। এর পেছনে থেকে কাজ করে চৌম্বকক্ষেত্র। তবে আরও মৌলিকভাবে এটা আসলে কোয়ান্টাম কণার ওপর নির্ভর করে। কিন্তু প্রকৃতির চার মৌলিক বলের মধ্যে এক মহাকর্ষেরই কোনো কোয়ান্টাম ধর্ম পাওয়া যায়নি। তাই কেউ জানে না মহাকর্ষীয় ক্ষেত্রের উৎস কী বা এর অভ্যন্তরে কণারা কীভাবে কাজ করে। কোয়ান্টাম তত্ত্ব আবার আপেক্ষিকতার মতো স্থানের বক্রতা স্বীকার করে না। এতে অবশ্য অসুবিধা হয় না। কারণ, ইলেকট্রনের মতো ছোট জায়গায় মহাকর্ষ অন্য বলের তুলনায় অনেক অনেক দুর্বল। গ্রহ-নক্ষত্রের বেলায় স্থানের বক্রতা সহজে দৃশ্যমান ও হিসাবযোগ্য। ইলেকট্রনের বেলায় তা শুধু অনুভবের অযোগ্যই নয়, গাণিতিকভাবে অসম্ভব। মহাকর্ষ নিয়ে কাজ করতে গেলেই কোয়ান্টাম তত্ত্বে চলে আসে অসীমের প্রয়োজনীয়তা। চলে অসীমবার একটি পরীক্ষা চালানোর প্রয়োজনীয়তাও।

এখানেই সার্বিক আপেক্ষিকতার সঙ্গে কোয়ান্টাম তত্ত্বের বিরোধ। অথবা বলা যায় দুর্বলতা। আইনস্টাইনের তত্ত্বে মহাকর্ষ হলো স্থান-কালের বক্রতার বহিঃপ্রকাশ। অন্যদিকে কোয়ান্টাম তত্ত্ব বলে, যেকোনো বল আসলে ক্ষুদ্র ক্ষুদ্র বিচ্ছিন্ন খণ্ডের সমাবেশ। এসব খণ্ডের নাম কোয়ান্টাম। বহুবচনে কোয়ান্টা।

লাতিন কোয়ান্টা কথাটার শাব্দিক অর্থ পরিমাণ। কোনো ভৌত বৈশিষ্ট্যের সর্বনিম্ন বিচ্ছিন্ন অংশ বোঝানোর জন্য শব্দটার আবির্ভাব। ‘সর্বনিম্ন’ শব্দ থেকেই বোঝা যায়, এ বৈশিষ্ট্যগুলো বিচ্ছিন্ন প্রকৃতির। অন্য অর্থে, কোয়ান্টায়িত। যেমন আলোর কোয়ান্টাম হলো ফোটন কণা। কোয়ান্টাম তত্ত্বের অন্যতম কর্ণধার ম্যাক্স প্ল্যাঙ্ক ১৯০০ সালে শব্দটা ব্যবহার করেন। সে সময়ে তিনি জ্বলজ্বলে বস্তুর বিকিরণ নিয়ে কাজ করছিলেন। জানতে চাইছিলেন, কেন তাপমাত্রা বাড়লে বিকিরণ লাল থেকে কমলা ও পরে নীল হয়। এটা করতে গিয়ে পেলেন একটি সমীকরণ। এতে শক্তির একককে স্বতন্ত্র বা আলাদাভাবে প্রকাশ করলেন। দেখলেন, একটি নির্দিষ্ট মাত্রার বিচ্ছিন্ন তাপমাত্রায় জ্বলজ্বলে বস্তু থেকে নির্গত শক্তি বর্ণালিতে ভিন্ন ভিন্ন রঙে ধরা দেয়। এ থেকেই এল বিচ্ছিন্নতার ধারণা।

আগেই বলেছি, কোয়ান্টাম তত্ত্ব বলে, প্রকৃতির বল ক্ষুদ্র ক্ষুদ্র কোয়ান্টায় গঠিত। তাহলে মহাকর্ষকেও তা–ই হতে হবে। স্থান-কালও তাহলে বিচ্ছিন্ন অংশ নিয়ে গঠিত হবে। হয়তোবা অতিক্ষুদ্র কাঠামোয় স্থান-কালও মৌলিক একক দিয়েই গঠিত। কিন্তু সমস্যা হলো, সার্বিক আপেক্ষিকতা কোয়ান্টার অস্তিত্বের কথা স্বীকার করে না। অথবা জানে না। আইনস্টাইনের মহাকর্ষ প্রকৃতিগতভাবে অবিচ্ছিন্ন।

এ পর্যায়ে বিচ্ছিন্ন ও অবিচ্ছিন্ন চলক সম্পর্কে একটুখানি জানা প্রয়োজন। গণিত ও পরিসংখ্যান থেকে মূলত ধারণাটির উৎপত্তি। যে চলকের মানে নির্দিষ্ট দুটি সংখ্যার মধ্যে অন্য সংখ্যা হতে পারে না, সেটি বিচ্ছিন্ন চলক। যেমন স্বাভাবিক সংখ্যাগুলো হলো ১, ২, ৩,...ইত্যাদি অসীম পর্যন্ত। ১ ও ২–এর মাঝে কেউ নেই। এমন রাশিগুলোর সেট বিচ্ছিন্ন। আবার বাস্তব সংখ্যার কথা ধরুন। ১ ও ২–এর মাঝখানে আছে অসীমসংখ্যক সংখ্যা। শুধু কি তা–ই! ১.১ ও ১.২–এর মাঝেই আছে অসীম সংখ্যা। একই কথা খাটে ১.১১ ও ১.১২-এর জন্য। আসলে যেকোনো দুই সংখ্যার মাঝেই অসীমসংখ্যক সংখ্যা আছে। বাস্তব সংখ্যারা তাই অবিচ্ছিন্ন। এদের মধ্যে নেই কোনো গ্যাপ বা ফাঁকা জায়গা।

মহাকর্ষ অবিচ্ছিন্ন। এ কথার অর্থ হলো, স্থান বা কালের মাঝে কোনো ফাঁকা নেই। যেকোনো দুটি সময় বা স্থানের মাঝে আছে অন্য কোনো সময় বা স্থান। এরই নাম স্থান-কাল পরম্পরা (Space-Time Continuum)। কিন্তু একটি বল হিসেবে একে তো বিচ্ছিন্ন ধরনের আচরণ করতে হবে। মহাবিশ্বের সর্বজনীন তত্ত্ব পেতে তাই দরকার এমন তত্ত্ব, যা মহাকর্ষকে কোয়ান্টার তুলির আঁচড়ে চিত্রায়িত করতে পারবে। আর ঠিক এখানেই লুপ কোয়ান্টাম গ্র্যাভিটি (এলকিউজি) তত্ত্বের আবির্ভাব। পদার্থবিদ্যার দুই আলাদা তত্ত্বকে জোড়া দেওয়ার ক্ষেত্রে অন্যতম প্রতিশ্রুতিশীল এক তত্ত্ব।
কোয়ান্টাম তত্ত্ব ও সার্বিক আপেক্ষিকতায় বড় একটি বিরোধ হলো স্থান-কালের ভূমিকা নিয়ে। কোয়ান্টাম তত্ত্বে স্থান-কাল নিছক একটি পটভূমি বা ঘটনার মঞ্চ। সে মঞ্চে বিকৃতি বা বক্রতা সৃষ্টি হতে পারে। সেই বক্রতা পাল্টাতে পারে কণার গতিপথও। কিন্তু ওইটুকুই। সবকিছু ঘটে সেই পটভূমির উপরিভাগে। কিন্তু সার্বিক আপেক্ষিকতায় স্থান-কাল কোনো অভিনেতার নাট্যমঞ্চ নয়। এখানে স্থান-কাল নিজেই অভিনেতা। এখানে আগে থেকে মঞ্চই থাকে না। অভিনেতা নিজেই সে মঞ্চ তৈরি করে। সার্বিক আপেক্ষিকতা হলো স্থান-কালের বক্রতার ভাষা। আর বক্রতা তৈরিই করে মহাকর্ষ।

মহাকর্ষ তো আসলে স্থান-কালের গতিবিদ্যাই। মহাকর্ষের কোয়ান্টাম তত্ত্ব পেতে তাই স্থান-কালের কোয়ান্টাম তত্ত্ব চাই। স্থান-কালকে কোয়ান্টায়িত করা গেলেই কেল্লা ফতে! আর এ কাজই করে লুপ কোয়ান্টাম গ্র্যাভিটি। লুপ নামটা দেওয়ার কারণ আছে। এমনিতে লুপ মানে ফাঁস বা এমন কিছু, যা ঘুরে আগের জায়গায় ফিরে আসে। লুপ কোয়ান্টাম গ্র্যাভিটি বা এলকিউজি তত্ত্বে আইনস্টাইনের সমীকরণ নতুন করে লেখা যায়। তবে পয়েন্ট বা বিন্দুর বদলে এখানে সমীকরণ প্রকাশ করা হয় রেখার ধারণা দিয়ে। এই রেখাগুলো বক্র, ঘুরে আবার নিজের সঙ্গে এসে মেলে; অর্থাৎ ফাঁস বা লুপ। স্থান-কাল এ তত্ত্বে মহাকর্ষীয় ক্ষেত্রের কোয়ান্টায়িত লুপ। যার নাম স্পিন নেটওয়ার্ক, অর্থাৎ অনেকগুলো লুপ মিলে গড়ে ওঠে স্থান-কাল। এর ফলে পদার্থবিদ্যায় কোনো পরিবর্তন আসে না। তবে কিছু হিসাব-নিকাশ সহজ হয়। বিশেষ করে স্থান-কালকে কোয়ান্টায়িত করার কাজ।

প্রশ্ন হলো, স্থান-কালকে কোয়ান্টায়িত করার মানে কী? এর মানে হলো, মৌলিক একটি একক বা বিচ্ছিন্ন খণ্ডের অস্তিত্ব আছে অতিক্ষুদ্র, অ–ইন্দ্রিয়গ্রাহ্য ও সূক্ষ্ম কাঠামোয়। যেমন ধরুন একটি ছবি। একে জুম করতে থাকলে একসময় দেখবেন, মসৃণ ছবিটায় ফুটে উঠবে বহু ছোট ছোট বর্গ। এদের নাম পিক্সেল। স্থান-কালের ব্যাপারটাও এর সঙ্গে তুলনীয়। জুম ইন করে ছোট ছোট এককের দিকে যেতে থাকলে দেখা যাবে, স্থান-কাল অবিচ্ছিন্ন বা মসৃণভাবে ভবিষ্যতের দিকে ছুটে চলছে না। চলছে বিচ্ছিন্ন এক ঘড়ির দ্রুত  টিকের মতো। চলাচলের পথটা মসৃণ নয়; বরং এ যেন স্থান-কালের এক পদক্ষেপ থেকে আরেক পদক্ষেপে থেমে থেমে হামাগুড়ি দিয়ে এগিয়ে যাওয়া।

স্থান-কালের এ কোয়ান্টায়ন হয় প্ল্যাঙ্ক স্কেলে। খুব ক্ষুদ্র দৈর্ঘ্য, সময়ে বা শক্তিতে৷ $১০^৯$ জুল শক্তি, $৫×১০^{-৪৪}$ সেকেন্ড ব্যাপ্তি বা $১০{-৩৫}$ মিটার দৈর্ঘ্যকে প্ল্যাঙ্ক স্কেল ধরা হয়। শক্তির পরিমাণটা প্ল্যাঙ্ক ভরের সমতুল্য পরিমাণ (আইনস্টাইনের ভর-শক্তির সমীকরণ E = mc2 থেকে)। আর প্ল্যাঙ্ক দৈর্ঘ্য প্রোটনের ১০ লাখ-কোটি-কোটি গুণ ছোট। প্ল্যাঙ্ক স্কেল পর্যন্তই শক্তি ও পদার্থের অর্থপূর্ণ পরিমাপ সম্ভব। মজার ব্যাপার হলো, প্ল্যাঙ্ক স্কেলে এসে কোয়ান্টাম তত্ত্ব ও সার্বিক আপেক্ষিকতা—দুটিই মুখ থুবড়ে পড়ে। কোনোটির পূর্বাভাসই কাজ করে না। মহাবিশ্বের জন্মের ঠক পরপর এমন অবস্থা ছিল। আরও সঠিক করে বললে, জন্মের $১০^{-৪৩}$ সেকেন্ড পরে ছিল সে অবস্থা। মহাবিশ্বের এই বিশেষ সময়টার নামও প্ল্যাঙ্ক যুগ। সে সময়ের অবস্থার কেমন ছিল বা সেটা কীভাবে হয়েছিল তা বলতে পারে না দুই তত্ত্বের কোনোটি।

কোয়ান্টায়নের একটি দারুণ সুবিধা হলো সিঙ্গুলারিটি সমস্যার সমাধান। আইনস্টাইনের তত্ত্বে অসীম ঘনত্ব ও মহাকর্ষের স্থানে তৈরি হয় সিঙ্গুলারিটি (বাংলায় অনন্যতা পরম বিন্দু)। এই যেমন মহাবিশ্বের শুরুতে বা কৃষ্ণগহ্বরের কেন্দ্রে। যেখানে অসীম মহাকর্ষ সব পদার্থকে টেনে নিয়ে গেছে একটি বিন্দু বা রেখায়। আয়তনকে করেছে শূন্য। শুনতে রোমহষর্ক হলেও এসব কথা আসলে তত্ত্বের দুর্বলতার প্রকাশ। এ জন্যই আমরা ঠিক জানি না কৃষ্ণগহ্বরের কেন্দ্র বা বিগ ব্যাংয়ের সময়ের অবস্থা। মহাকর্ষের প্রভাবে সৃষ্ট এ সিঙ্গুলারিটির নাম মহাকর্ষীয় সিঙ্গুলারিটি। তবে সংজ্ঞাই বলছে, সিঙ্গুলারিটি অতিশয় ক্ষুদ্র। সে হিসাবে বৈশিষ্ট্যের দিক থেকে এটি কোয়ান্টামধর্মী। এ কারণেই একে বুঝতে হলে চাই কোয়ান্টাম মহাকর্ষ তত্ত্ব। কল্পসাহিত্যে তাই কোয়ান্টাম সিঙ্গুলারিটি কথাটা বেশ জনপ্রিয়ও বটে। এর ব্যবহার দেখা যায় স্টার ট্রেক, ফিউচারামার মতো মুভিগুলোয়।

লুপ কোয়ান্টাম মহাকর্ষে সিঙ্গুলারিটি তৈরি হয় না। এর বদলে আছে অতিশয় ক্ষুদ্র ও অপরিসীম ঘন বস্তুখণ্ড। এই অতিশয় ক্ষুদ্র বস্তুখণ্ড দেখতে কেমন, সে সম্পর্কে আমাদের কোনো ধারণা নেই। স্পিন নেটওয়ার্ক নামের পিক্সেল–জাতীয় স্থান-কালের কিছু গাণিতিক সূত্র পাওয়া গেছে। তবে তত্ত্বটি এখনো অসম্পূর্ণ। ছোট কাঠামোয় তত্ত্বটি মহাকর্ষকে ভালো ব্যাখ্যা করতে পারে। যেটা পারা উচিত বড়-ছোট সব ধরনের কাঠামোয়। তত্ত্বটাকে পৃথিবী ও সূর্যের সম্পর্কের মতো সাধারণ পরিস্থিতিতেও কাজ করতে হবে এবং ফলাফল দিতে হবে সার্বিক আপেক্ষিকতা বা নিউটনীয় মহাকর্ষের মতো। এই দুই তত্ত্বই এ ক্ষেত্রে ঠিকঠাক কাজ করতে হবে। অন্যভাবে বললে, এলকিউজির মধ্যেই সার্বিক আপেক্ষিকতা থাকতে হবে।

এখনো জানা যায়নি, আসলে তা আছে কি না। এর জন্য ক্ষুদ্রতম কাঠামোর পিক্সেল-সদৃশ কোয়ান্টাম স্থান-কালকে জুম আউট করে পেতে হবে আপেক্ষিকতার মসৃণ ও তরঙ্গায়িত স্থান-কাল। এখন পর্যন্ত কেউ কাজটা করতে পারেননি।

সমস্যা আরও আছে। বিশেষ আপেক্ষিকতা বলে, আমাদের স্থান ও কালের পরিমাপ নির্ভর করে বেগের ওপর। কিন্তু পদার্থবিদ্যার মৌলিক স্তর সবার কাছে একই হওয়া উচিত। কিন্তু ভিন্ন ভিন্ন পর্যবেক্ষক স্থান-কালের কোয়ান্টায়িত পিক্সেলের ভিন্ন ভিন্ন দৃশ্য দেখলে তাদের কাছে পদার্থবিদ্যা জিনিসটাই হবে সম্পূর্ণ আলাদা।

১৯৮৬ সালে এলকিউজি তত্ত্বের সূচনা ঘটে। ভারতীয় পদার্থবিদ অভয় অষ্টকার আইনস্টাইনের আপেক্ষিকতাকে নতুন করে সূত্রায়িত করেন। এতে আপেক্ষিকতা পদার্থবিদ্যার অন্যান্য মৌলিক নীতির কাছাকাছি চলে আসে। বিশেষ করে ইয়াং-মিলস তত্ত্বের কাছাকাছি হয়। ইয়াং-মিলস তত্ত্বকে কণাপদার্থবিদ্যার স্ট্যান্ডার্ড মডেলের ভিত্তি বলা চলে। অষ্টকারের কাজে আগ্রহী হন টেড জ্যাকবসন ও লি স্মোলিন। তাঁরা দেখলেন, কোয়ান্টাম মহাকর্ষের সমীকরণ অষ্টকার চলক দিয়ে লিখলে লুপের মাধ্যমে সমাধান আসে। পরে কার্লো রোভেলি ও স্মোলিন লুপের সমাধানের মাধ্যমে পটভূমির ওপর অনির্ভরশীল কোয়ান্টাম গ্র্যাভিটি তত্ত্ব সংজ্ঞায়িত করেন। জর্জ পুলিন ও জার্জি লেভানডফস্কি দেখেন, তত্ত্বের সুসংগতির জন্য লুপ থাকা বাধ্যতামূলক। তত্ত্বকে সূত্রায়িত করতে পরস্পরছেদী লুপ বা গ্রাফ দরকার।

১৯৯৪ সালে রোভেলি ও স্মোলিন দেখান, ক্ষেত্রফল ও আয়তনের কোয়ান্টাম অপারেটরের আছে বিচ্ছিন্ন ধরনের বর্ণালি। তার মানে জ্যামিতি এখানে কোয়ান্টায়িত। এর মাধ্যমে খুলে গেল কোয়ান্টাম জ্যামিতির পথ। পরে থমাস থিম্যান দেখান, পটভূমি থেকে স্বাধীন তত্ত্ব গাণিতিকভাবে সংগতিপূর্ণ। বর্তমানে বিশ্বজুড়ে অন্তত ৩০টি দল এলকিউজি নিয়ে গবেষণায় রত। একপর্যায়ে এসে গবেষণা দুই দিকে বেঁকে যায়। একটি হলো প্রথাগত লুপ কোয়ান্টাম গ্র্যাভিটি। অপরটি স্পিন ফোম থিওরি। এলকিউজি থেকে পাওয়া সবচেয়ে আধুনিক তত্ত্বের নাম লুপ কোয়ান্টাম কসমোলজি। যেখানে বিগ ব্যাংকে ধারণা করা হয় বিগ বাউন্সের অংশ। যাতে বলা হয় মহাবিশ্বের সংকোচন (বিগ ক্রাঞ্চ) ও প্রসারণ হয় পালাক্রমে৷ এক মহাবিশ্বের সংকোচন থেকে জন্ম হয় পরের মহাবিশ্বের।

লুপ কোয়ান্টাম গ্র্যাভিটির প্রবল প্রতিদ্বন্দ্বী স্ট্রিং থিওরি। মৌলিকভাবে দুই তত্ত্ব একদম আলাদা। এলকিউজি কাজ করে স্থান-কালকে বিচ্ছিন্ন খণ্ড ধরে নিয়ে। ওদিকে স্ট্রিং থিওরি বলে, সব বস্তু মৌলিকভাবে স্ট্রিং বা সুতা দিয়ে তৈরি। স্ট্রিংয়ের প্রান্ত খোলা বা নিজের সঙ্গেই মিশে থাকতে পারে। এদের আছে কম্পন। হতে পারে লম্বা, আবার ভেঙে যেতে পারে বা জোড়াও লাগতে পারে একে অপরের সঙ্গে। এগুলো থেকেই মূর্ত হয় বস্তু ও স্থান-কাল। অন্যদিকে এলকিউজি বস্তু নিয়ে ভাবে না। বস্তু থাকে স্থান-কালের মধ্যে। এটি তাই কাজ করে স্থান-কালের বৈশিষ্ট্য নিয়ে। আইনস্টাইনের মহাকর্ষের মসৃণ পটভূমিকে এখানে স্ট্রিংয়ের কম্পন দিয়ে প্রকাশ করা হয়, যাতে প্রকাশিত হয় কোয়ান্টাম বৈশিষ্ট্য৷ স্ট্রিং থিওরি বলে, স্থান-কালের মাত্রা ১০টি। এলকিউজি উচ্চতর মাত্রায় কাজ করে না। স্ট্রিং থিওরি বলে অতিপ্রতিসাম্যের কথা। যার অর্থ হলো, পরিচিত সব কণার আছে অনাবিষ্কৃত জোড়া। এলকিউজি তত্ত্বে এমন কোনো কথা নেই। দুই তত্ত্বের বিরোধ জড়িয়েছে সমর্থকদেরও। এক দল আরেক দলের কোনো বৈজ্ঞানিক সম্মেলনে যায় না।

তরুণ গবেষকেরা দুই তত্ত্বকে একীভূত করারও চেষ্টা করছেন। এলকিউজির বড় একটি অসুবিধা হলো, স্থান-কালের ছোট পরিসর থেকে জুম আউট করে বড় কাঠামোয় চলে আসা। বড় কাঠামোয় এসে এর আইনস্টাইনের আপেক্ষিকতার ফলাফল দিতে পারতে হবে। কিন্তু তা হচ্ছে না তত্ত্বে। আরও বড় সমস্যা হলো, মহাকর্ষহীন অবস্থায় এটি অকার্যকর। আইনস্টাইনের বিশেষ আপেক্ষিকতা বলছে, পর্যবেক্ষকের বেগের ওপর নির্ভর করে বস্তুর দৈর্ঘ্য সংকোচন হবে। একই সঙ্গে হবে কাল দীর্ঘায়ন ও ভর বৃদ্ধি। এককথায়, প্রভাবিত হবে স্থান-কালের খণ্ড। ভিন্ন ভিন্ন পর্যবেক্ষক স্থান-কালের পিক্সেলের ভিন্ন ভিন্ন আকার দেখবে। অন্যদিকে আইনস্টাইনের তত্ত্বের মৌলিক মূলনীতি বলে, পদার্থবিদ্যার মৌলিক সূত্র বেগের ওপর নির্ভর করবে না। ফলে বিচ্ছিন্ন খণ্ড নিয়ে কাজ করতে গেলে আপেক্ষিকতার সাথে বিরোধ তৈরি হয়ে যায়।

থিম্যানের নেতৃত্বে একদল গবেষক আবার এলকিউজিতে অতিপ্রতিসাম্য ও উচ্চ মাত্রা অন্তর্ভুক্ত করেছেন। থিম্যানের ছাত্র নর্বার্ট বোডেনডরফার স্ট্রিং থিওরির সমস্যা দূর করতে কাজে লাগিয়েছেন এলকিউজির ধারণা। তবে অনেকেই এখনো এলকিউজি নিয়ে সংশয়বাদী। এলকিউজির অন্যতম প্রতিষ্ঠাতা কার্লো রোভেলি আবার স্ট্রিং তত্ত্ব ও এলকিউজিকে একই মুদ্রার দুই পিঠ ভাবতে নারাজ। তাঁর মতে, আশির দশকের সেই আবেদন স্ট্রিং তত্ত্ব হারিয়েছে। তবে পুলিন বলছেন, দুই তত্ত্বই এখনো সম্ভাবনাময়ী।

লুপ কোয়ান্টাম গ্র্যাভিটি এখনো অসম্পূর্ণ-এতটুকু বলতে বাধা নেই। রয়েছে বড় বড় সীমাবদ্ধতাও। এটি এখনো বলতে পারে না, কীভাবে কোয়ান্টাম দশা থেকে তৈরি হয় স্থান-কালের জ্যামিতি। কোয়ান্টায়িত স্থান-কাল দিয়ে বলার উপায় নেই, কোনটা সমতল জায়গা আর কোনটা কৃষ্ণগহ্বরের মতো অতিশয় বক্র। ফলে স্ট্রিং বা এলকিউজি তত্ত্বের কোনোটি থেকেই সমাধানযোগ্য পথ পাওয়া যাচ্ছে না৷ দুটি তত্ত্বই কঠিন সময় পার করছে। এরা টিকে থাকবে, নাকি নতুন প্রস্তাবিত তত্ত্ব আসবে, তা সময়ই বলে দেবে। আদৌ যদি মহাবিশ্বের কোনো থিওরি অব এভরিথিং বা সার্বিক তত্ত্ব থেকে থাকে, তবে। এমনও তো হতেই পারে, মহাবিশ্বের কোনো সার্বিক তত্ত্বই নেই। সেটাও এক সম্ভাব্য অবস্থা।

সূত্র:

১. কার্লো রোভেলি, ২০১৬, সেভেন ব্রিফ লেসনস অন ফিজিকস

২. ইন্টারনেট: কোয়ান্টা ম্যাগাজিন, স্ট্যানফোর্ড ডট এজু, কোয়ান্টামলি ডটকম, স্পেস ডটকম, ইউনিভার্স টুডে, সিমেট্রি ম্যাগাজিন

- https://www.quantamagazine.org/string-theory-meets-loop-quantum-gravity-20160112/
- https://einstein.stanford.edu/content/relativity/a11758.html
- http://quantumly.com/m.what-is-a-quantum-or-quanta-definition.html
- https://www.space.com/quantum-gravity.html
- https://www.universetoday.com/50702/loop-quantum-gravity/
- https://www.symmetrymagazine.org/article/june-2013/unification-of-forces?language_content_entity
- https://www.space.com/loop-quantum-gravity-space-time-quantized
- https://www.space.com/quantum-gravity.html
