# আসলেই কি বর্তমানে মতো কোনো সময় নেই?

১৯৯৫ সালের মে মাসে কার্লো রোভেলি ও লি স্মোলিন নিউক্লিয়ার ফিজিক্স বি জার্নালে একটি গবেষণাপত্র প্রকাশ করেন। এরিয়া ও ভলিউমের বিচ্ছিন্নতা নিয়ে এতে আলোকপাত করেন। এতে তাঁরা বলেন, কোনো ভৌত পৃষ্ঠের ক্ষেত্রফল বা অঞ্চলের আয়তন প্ল্যাংক স্কেলের মতো নিখুঁত কের পরিমাপ করতে পারলে দেখা যাবে, যেকোনো পরিমাপের ফলাফল এখানে প্রদত্ত বিচ্ছিন্ন বর্ণালী মধ্যে পড়বে।

জেনেভার সার্ন গবেষণাকেন্দ্রে আছে পৃথিবীর সবচেয়ে শক্তিশালী কোলাইডার। উচ্চ-শক্তির কণাদের মধ্যে সংঘর্ষ ঘটানো হয় এখানে। এসব সংঘর্ষ থেকে বস্তুর এক অ্যাটোমিটার ($১০^{-১৮}$ মিটার) আকারের দূরত্বের বৈশিষ্ট্য পরিমাপ করা যায়। কিন্তু প্ল্যাংক স্কেল পর্যন্ত নিখুঁত করে মাপা নিকট ভবিষ্যতেও হয়তো সম্ভব নয়। তবে তাত্ত্বিকদের অর্জন নিয়ে সন্দে‌‌‌হ কোনো অবকাশ নেই। অন্তত ৮০ বছর ধরে সার্বিক আপেক্ষিকতা ও কোয়ান্টাম থিওরি একে অপর থেকে দূরে দূরে থেকেছে। এখন বেশ কজন নিবেদিত তাত্ত্বিকের পরিশ্রমের ফসল হিসেবে মিলনের একটি সম্ভাবনা দেখা যাচ্ছে।
মাথায় রাখতে হবে, এটি ছিল এমন এক তত্ত্ব যা স্থান ও কাল সম্পর্কে সব জ্ঞান সার্বিক আপেক্ষিকতা থেকে আরেকটি কাঠামোতে নিয়ে এসেছে। আর সে কাঠামোটা দেখতে কোয়ান্টাম ফিল্ড থিওরির মতো। এখান থেকে পাওয়া গেছে এক গুচ্ছ সমীকরণ। যেগুলো সমাধান করতে গোলমেলে ও দীর্ঘ রিনর্মালাইজেশন প্রক্রিয়ার সাহায্য লাগে না। এছাড়াও দেখা যায়, এর সমাধানগুরৈা স্থানাঙ্কব্যবস্থার ওপর নির্ভর করে না। এটা সত্যি সত্যিই স্থানকালের কোনোরকম পটভূমির ওপর নির্ভর করছে না। এছাড়াও এটা ছিল এমন এক তত্ত্ব, যা নির্মিত হয়েছে স্বীকৃত ও বাস্তবে পরীক্ষিত ও নির্ভরযোগ্য কাঠামোর ভিত্তিিতে। সুপারসিমেট্রি বা গুপ্ত মাত্রার ধারণা নিয়ে এসে ভৌত বাস্তবতার অনুমান করার প্রয়োজন ফুরিয়েছে।

তবে তাত্ত্বিকদের আনন্দের মুহূর্ত দীর্ঘস্থায়ী হলো না। রোভেলি ও স্মোলিনের গবেষণাপত্র প্রকাশিত হবার মাত্র চার মাস আগের কথা। একটি সম্মেলনে এডওয়ার্ড উইটেনের বলা কিছু কথা থেকে শুরু হয়ে গেল দ্বিতীয় সুপারস্ট্রিং বিপ্লব।

১৯৮৪ সালের প্রথম বিপ্লবের পরে সুপারস্ট্রিং গবেষণার প্রতি আগ্রহের জোয়ার বয়ে যায়। ১৯৮৭ সালে এ জোয়ার চূড়ায় পৌঁছে। সে বছর প্রকাশিত হয় সবচেয়ে বেশি গবেষণাপত্র। গ্রিন ও শোয়ার্জের প্রাথমিক সেই গবেষণাপত্রটিও সবচেয়ে বেশিবার সাইটেশন পায় সে বছর। কিন্তু সমস্যাও বাড়তে থাকায় আগ্রহ আবার কমতে শুরু করে।

সবচেয়ে ভয়ঙ্কর সমস্যাটা ছিল তত্ত্বটার ইউনিকনেস বা অনন্যতা নিয়ে। একদিকে সুপারস্ট্রিং থিওরির এত এত রূপ। তার ওপর স্থানের বাড়তি মাত্রাগুলোকে লুকানোর জন্য সম্ভাব্য কালাবি-ইয়াও স্পেসও বেড়ে গেল ব্যাঙের ছাতার মতো। কোনটা রেখে কোনটা বাছাই করা হবে তা বোঝার কোনো উপায় থাকল না। এ তত্ত্বে কাজ করে কেউ কেউ জনপ্রিয় হচ্ছিলেন, কিন্তু সম্মানজনক প্রতিষ্ঠানগুলোতে চাকরির অফারের সংখ্যা কমে আসছিল। ১৯৯৪ সালের শেষ দিকে দেখা গেল, সুপারস্ট্রিং তত্ত্বে আগ্রহী হওয়া অনেকেই নিরুৎসাহিত হয়ে পড়েছেন। কেউ কেউ তো এটা ছেড়ে অন্য ফিল্ডেই চলে গেছেন।

একনিষ্ট সমর্থকরা থেকে গেলেন। তাঁরা ভাবলেন, সুপারস্ট্রিং থিওরি এখনও প্রচুর সম্ভাবনাময়ী। এর কাঠামোটা দারুণ সুন্দর। এতই সুন্দর যে প্রকৃতির ব্যাখ্যা এর কোনো না কোনো ভূমিকা থাকবেই। অথবা সম্ভবত ইতোমধ্যে এত বেশি কাজ করা হয়েছে যে এখন আর একে ব্যর্থ হতে দিতেই নারাজ তাঁরা। সুপারস্ট্রিং তাত্ত্বিকরা নিজেদেরকে বুঝিয়েছে, এটাই থিওরি অব এভরিথিং বা সার্বজনীন তত্ত্বের একমাত্র পথ। আর কোনো রাস্তা নেই। অনেকেই সুখের সাগরে ভেসে গিয়ে অন্য পথের কথা ভাবেইনি। থিওরি অব এবরিথিং না হোক, কোয়ান্টাম গ্র্যাভিটির অন্য পথ তো থাকতে পারে।

কোনো কোনো সুপারস্ট্রিং তাত্ত্বিক আবার সুপারগ্র্যাভিটির সাহাযে্য করা কিছু হিসাবের ভিত্তিতে বলেছিলেন, স্থানকালের মাত্রার প্রকৃত সংখ্যা দশ নয়, বরং এগারো। সবকিছুই যেন কিছুটা নিয়ন্ত্রণের বাইরে চলে যাচ্ছে। ১৯৯৫ সালের মার্চ মাসে সাউদার্ন ক্যালিফোর্নিয়া বিশ্ববিদ্যালয়ে স্ট্রিং থিওরি নিয়ে একটি সম্মেলন অুনষ্ঠিত হয়। উইটেন এখানে একটি সাহসী অনুমান তুলে ধরেন। এমনও তো হতে পারে, পাঁচটি আলাদা সুপারস্ট্রিং থিওরি ও সুপারগ্র্যাভিটি আসলে একটিমাত্র সর্বব্যাপী এগারো-মাত্রিক কাঠামোর ভিন্ন ভিন্ন রূপ বা নমুনা। তিনি একে নাম দিলেন এম-থিওরি। তবে এম (M) অক্ষরটার নির্দিষ্ট কোনো অর্থ বা গুরুত্ব তিনি উল্লেখ করেননি।

কিন্তু সুপারস্ট্রিং থিওরি এগারো নয়, দশ মাত্রায় সূত্রবদ্ধ হয়েছিল। ব্যাঁ, আরেকি মাত্রাকে জায়গা দেওয়া সম্ভব। তবে সেজন্য স্ট্রিংয়ের অর্থ পাল্টে ফেলতে হবে। এটা আসলে মেমব্রেন বা ব্রেইন (brane) নামের আরও উচ্চমাত্রিক বস্তুর একটি রূপ (এখান থেকে অবশ্য এম-থিওরির নামের একটা উৎস (মেমব্রেন) পাওয়া যায়)। এর মাধ্যমে মনোযোগ স্ট্রিং থেকে সরে গেল মেমব্রেনের দিকে। ব্রিটিশ স্ট্রিং তাত্ত্বিক মাইকেল ডাফ তো বললেনই, এম-থিওরিরই পূর্ব নাম স্ট্রিং থিওরি।

এটা আসলে কোনো থিওরি ছিল না, ছিল শুধু একটি কনজেকচার বা অনুমান। উইটেন দশ-মাত্রিক সুপারস্ট্রিং থিওরি ও এগারো-মাত্রিক সুপারগ্র্যাভিটিকে সমতুল্য প্রমাণ করলেন। কিন্তু এম-থিওরিকে সূত্রবদ্ধ করতে ব্যর্থ হলেন। শুধু অনুমান করলেন, এই থিওরির অস্তিত্ব অবশ্যই থাকবে। আমার অভিজ্ঞতা বলে, এম-থিওরি যে আসলে কোনো তত্ত্বই না তা স্ট্রিং থিওরির অনেক সাধারণ পাঠকেরই চোখ এড়িয়ে যায়। আজ পর্যন্ত কেউ জানে না এম-থিওরির চেহারা কেমন। অবশ্য এম-থিওরির সম্ভাব্য কাঠামো নিয়ে অনেক তাত্ত্বিক কাজ করেছেন। বাস্তবে এম-থিওরি কেবলই একটি অনুমান বা প্রত্যাশার নাম। যে প্রত্যাশা বলে, একটি অনন্য এগারো-মাত্রিক সুপারস্ট্রিং থিওরি অবশ্যই থাকবে।

তবুও বহু তাত্ত্বিক বেশ জোশ নিয়ে কাজে নেমে পড়লেন। সুপারস্ট্রিং আবারও জনপ্রিয় হয়ে উঠল। আগ্রহ বাড়তে থাকল মানুষের। প্রতিষ্ঠানগুলো স্ট্রিং তাত্ত্বিকদেরকে চাকরি দেওয়ার জন্য কাড়াকাড়ি শুরু করে দিল। মাত্র কয়েক বছরের মাথায় পদার্থবিদ্যার বড় বড় প্রশ্নগুলোর জবাব খোঁজার প্রধান অবলম্বন হয়ে গেল তত্ত্বটা। জনপ্রিয় বেস্ট-সেলিং বইগুলোতে যৌক্তিকভাবেই এসব নিয়ে আলোচনা হতে থাকল। ব্রায়ান গ্রিনের ১৯৯৯ সালে প্রথম প্রকাশিত বই দ্য এলিগ্যান্ট ইউনিভার্স এমনই এক নমুনা।

ব্যাপারটা আসলে কখনোই দুটি পদ্ধতি একটিকে বেছে নেওয়ার
