# অতীতের ব্যর্থতা

১৬৮৭ সালে আইজ্যাক নিউটনের পিন্সিপিয়া প্রকাশেরর সাথে সাথে আধুনিক ভৌত বিজ্ঞান এর চূড়ান্ত শিখরে পৌঁছে যায়। এরপরেই মেকানিকস বা গতিবিদ্যা পরিপক্ক শাখা হিসেবে দাঁড়িয়ে যায়। এর ফলে কণার গতি নিয়ে পরিস্কার ও নিশ্চিত (deterministic) উপায়ে ব্যাখ্যা করা সহজ হয়ে গেল। নতুন এ বিজ্ঞানকে দেখে দারুণ পূর্ণাঙ্গ মনে হলো। এতই পূর্ণাঙ্গ মনে হলো যে ১৮শ শতকের শেষ দিকে নিউটনের সেরা উত্তরসূরী বিজ্ঞানী পিয়েরে সিমোঁ লাপ্লাস??? তাঁর সে বিখ্যাত উক্তিটি করলেন: হিসাব-নিকাশের অসীম ক্ষমতা এবং কোনো একটি নির্দিষ্ট সময়ে সব কণার বিন্যাসের পরিপূর্ণ জ্ঞান থাকলে নিউটনের সূত্র দিয়ে ভবিষ্যৎ বলা যাবে। একইরকম নিশ্চিতভাবে বলা যাবে পুরো মহাবিশ্বের অতীতও। কিছুটা ভয় সৃষ্টিকারী এ নিশ্চয়তাবাদী বক্তব্য নিয়ে সন্দেহ সবসময় ছিল। বক্তব্যের মধ্যে ছিল অহমিকার ছোঁয়া। প্রথমত, মানুষ যন্ত্রের মতো স্বয়ংক্রিয়ভাবে কাজ করে না। দ্বিতীয় কথা হলো নিউটনের সূত্রের অপূর্ণাঙ্গতা। হ্যাঁ, নিউটনের সূত্রের সুদূরপ্রসারী প্রভাব অনস্বীকার্য। কিন্তু সেসময়ে জানা ভৌত পৃথিবীর সবকিছুকেও নিউটনের সূত্র দিয়ে ব্যাখ্যা করা যেত না। এমন বহু অমীমাংসিত বিষয় ছিল, যা নিউটনীয় মতবাদের স্বনির্ভরতার ভিত্তিকে দুর্বল করে দিচ্ছিল। এই যেমন, নিউটনের আবিষ্কৃত মহাকর্ষের সার্বজনীন বিপরীত বর্গীয় সূত্রের [* এ সূত্র অনুসারে দূরত্ব দ্বিগুণ হলে মহাকর্ষীয় বল চার ভাগের এক ভাগ হয়ে যায়। দূরত্ব তিনগুণ হলে হয় নয় ভাগের এক ভাগ। আরও অনেক ক্ষেত্রেই দুটি রাশী এ নিয়ম মেনে চলে।] সত্যিকার বৈশিষ্ট্য ও উৎস নিয়ে ছিল প্রশ্ন। আরেকটি ব্যাপার ছিল, যা নিয়ে নিউটন নিজেও কোনো অনুমান করতে রাজি ছিলেন না। এছাড়াও ছিল আলোর ধর্মের ব্যাপারটি। নিউটন কিছুটা অনুমানের ওপর ভর করেও চলেছিলেন। তাঁর, অপটিকস বইয়ে তিনি আলোকে ছোট ছোট কণার প্রবাহ বলে অনুমান করে নেন। নিউটন ভৌত পৃথিবীকে পরমাণুবাদের দৃষ্টিকোণ থেকে দেখতেন। ফলে তাঁর এ ভাবনার উৎস সে দৃষ্টিকোণটাই।

## আলোর ধর্ম

আলোর প্রকৃতি বোঝার চেষ্টা চল্লতে থাকল। তবে ঊনবিংশ শতক পর্যন্ত তাতে সত্যিকার কোনো অগ্রগতি হয়নি। নতুন এ শতকের একদম শুরুর কথা। ১৮০১ সালে থমাস ইয়ং আলোর তরঙ্গ বৈশিষ্ট্যের পক্ষে অতিজোরালো প্রমাণ দেখালেন। প্রায় এক শ বছর আগেই অবশ্য নিউটনের সমসাময়িক ডাচ বিজ্ঞানী ক্রিশ্চিয়ান হাইগেন্স ব্যাপারটা আঁচ করেছিলেন। ইয়ং মূলত যে কাজটি করেছিলেন তাকে এখন আমরা ব্যাতিচার* বলি। এর একটি পরিচিত উদাহ হলো আলো ও অন্ধকারের পরপর উপস্থিতি। মজার ব্যাপার হলো নিউটন নিজেই ব্যাপারটা করে দেখিয়েছিলেন। ঘটনাটার নাম নিউটনের বলয়। এ ধরনের ফল পাওয়া যায় তরঙ্গ থেকে আসে। দুই সারি তরঙ্গের মিলন কেমন হবে তা নির্ভর করে তাদের পারস্পরিক স্পন্দনের ছন্দের ওপর। দুই তরঙ্গ একই দশায় থাকলে (একসঙ্গে চললে, মানে তরঙ্গের চূড়া ও খাঁজ সমতালে এগোলে) মিলিত তরঙ্গের বিস্তার বড় হয়ে যায়। আলোক তরঙ্গের ক্ষেত্রে এ অবস্থায় উজ্জ্বল আলোর ব্যান্ড দেখা যায়। আবার এক তরঙ্গের চূড়া আরেক তরঙ্গের খাঁজের সাথে মিলিত হলে দুই তরঙ্গ একে অপরকে নেই করে দেয়। ফলে মিলিত তরঙ্গের ফল হয় তরঙ্গহীনতা। তরঙ্গ হারিয়ে গেলে তৈরি হয় ধ্বংসাত্মক ব্যাতিচার। আলোর ক্ষেত্রে এ অবস্থায় পাওয়া যায় অন্ধকার ব্যান্ড। ফলে পরপর অন্ধকার ও আলোর ব্যান্ড দেখে তরঙ্গের উপস্থিতির ব্যাপারে নিশ্চিত হওয়া যায়। দেখে মনে হলো, ইয়ংয়ের পরীক্ষা ব্যাপারটার চূড়ান্ত মীমাংসা করে দিয়েছে। আলো একটি তরঙ্গ।

ঊনবিংশ শতক এগিয়ে চলল। আলোর সাথে তরঙ্গসদৃশ গতির সম্পর্ককে পরিস্কার মনে হলো। হ্যান্স ক্রিশ্চিয়ান ওরস্টেড? ও মাইকেল ফ্যারাডের আবিষ্কার থেকে দেখা গেল, বিদ্যুৎ ও চুম্নকত্ব একে অপরের ভাই ভাই। যদিও আগে এদেরকে পরস্পর সম্পর্কহীন মনে হত।

চিত্র ১: ক) একই তালে চলা তরঙ্গ, খ) বিপরীত তালে চলা তরঙ্গ

দেখা গেল, দুটোকে একত্র করে দারুণ এক সুসঙ্গত তত্ত্ব বানানো যাচ্ছে। কাজটা শেষ পর্যন্ত বাস্তবে করে দেখান জেমস ক্লার্ক ম্যাক্সওয়েল। অসাধারণ প্রতিভাবান এ বিজ্ঞানীকে আইজ্যাক নিউটনের সমপর্যায়ের বললে একটুও ভুল হবে না। ম্যাক্সওয়েলের সমীকরণ নামে পরিচিত তাঁর গড়া বিখ্যাত সমীকরণগুলো এখনও তড়িচ্চুম্বকত্বের ভিত্তি হিসেবে কাজ করে। ১৮৭৩ সালে প্রকাশিত ট্রিটিজ অন ইলেকট্রিসিটি অ্যান্ড ম্যাগনেটিজম পুস্তকে এগুলো প্রকাশিত হয়। বৈজ্ঞানিক প্রকাশনার জগতে এ বই অন্যতম একটি শ্রেষ্ঠ রচনা। ম্যাক্সওয়েল বুঝতে পারেন, এ সমীকরণগুলো তরঙ্গসদৃশ সমাধান দেয়। আর এ তরঙ্গগুলোর বেগ পরিচিত ভৌত ধ্রুবক দিয়েই বের করা যায়। আর দেখা গেল, সেই নির্দিষ্ট বেগটা আলোর বেগের সমান।

ঊনবিংশ শতকের পদার্থবিদ্যার সেরা আবিষ্কার এটি। অতএব আলো যে একটি তড়িচ্চুম্বকীয় তরঙ্গ তা সুপ্রতিষ্ঠিত হয়ে গেল। ম্যাক্সওয়েল ও তাঁর সমসাময়িকরা মনে করতেন, এ তরঙ্গগুলো সর্বত্র উপস্থিত স্থিতিস্থাপক মাধ্যম ইথারের মধ্যে সংঘটিত স্পন্দন। এক বিশ্বকোষের লেখায় তিনি বলেন, ভৌত তত্ত্বগুলোর মধ্যে ইথার সবচেয়ে প্রমাণিত বস্তু।

নিউটন ও ম্যাক্সওয়েলের পদার্থবিদ্যাকে আমরা ক্ল্যাসিকেল বা চিরায়ত পদার্থবিদ্যা বলতে পারি। ঊনবিংশ শতকের শেষ দিকেও এটিই ছিল নান্দনিক এক তাত্ত্বিক কাঠামো। লর্ড কেলভিন তো বললেন, পদার্থবিজ্ঞানের বড় বড় ভাবনাগুলোর কোনোটিই আর জানার বাকি নেই। এখন শুধু হিসাব-নিকাশ আরও আরও নির্ভুল করার কাজ বাকি। এ বক্তব্যে  কেউ একটুও অবাক হলো না। ঐ শতকের শেষ ভাগে তো জার্মানির এক তরুণকে পদার্থবিদ্যায় ক্যারিয়ার গড়ার ব্যাপারে সতর্ক করা হয়। বলা হয়, অন্য চিন্তা করতে হবে। পদার্থবিদ্যা তার গন্তব্যের শেষ প্রান্তে পৌঁছে গেছে। জানার প্রায় কিছুই অবশিষ্ট নেই। সেই তরুণের নাম ম্যাক্স প্ল্যাঙ্ক। আর আমাদের সৌভাগ্য, তিনি ঐ পরামর্শ কানে তোলেননি।

সত্যি বলতে, চিরায়ত পদার্থবিদ্যার সু… নান্দনিক প্রাসাদে অলরেডি চিড় ধরতে দেখা গেছে। ১৮০০-র দশকে দুই মার্কিন বিজ্ঞানী মাইকেলসন ও মর্লি একটি অসাধারণ পরীক্ষা চালান। তাঁদের প্রাথমিক উদ্দেশ্য ছিল, ইথারের মধ্য দিয়ে পৃথিবীর গতি দেখানো। তাঁরা ভাবলেন, ধরা যাক, আলো ইথার মাধ্যমে বয়ে চলা তরঙ্গ। সেক্ষেত্রে আলোর পরিমাপকৃত বেগ ইথারের সাপেক্ষে পর্যবেক্ষকের বেগের ওপর নির্ভর করবে। সমুদ্রের তরঙ্গের কথাই ভাবুন। তরঙ্গের আপাত বেগ নির্ভর করে জাহাজের বেগের ওপর। জাহাজ তরঙ্গের দিকে চললে তরঙ্গের পরিমাপকৃত বেগ কম মনে হবে। আর উল্টোদিকে চললে তরঙ্গের বেগ বেশি মনে হবে।

পরীক্ষার পরিবেশ এমনভাবে তৈরি করা হয় যাতে আলোর বেগ দুটি পরস্পর লম্বদিকে পরিমাপ করা যায়। ধরা যাক, কোনো কাকতালীয় কারণে পরীক্ষার সময় পৃথিবী ইথারের সাপেক্ষে স্থির আছে। শুধু সেক্ষেত্রেই আলোর দুইটি দিকে পরিমাপকৃত বেগ একই হবে। এটা ঘটে থাকলেও সেটা থেকে খহব সহজেই মুক্তি পাওয়া যায়। কয়েকমাস পরেই পৃথিবী সূর্যের চারপাশের কক্ষপথে ভিন্ন দিকে চলবে। কিন্তু মাইকেলসন ও মর্লি বেগের মানে কোনো পার্থক্য পেলেন না।

এ গরমিলের সমাধান পেতে অপেকরতে হলো আইনস্টাইনের আপেক্ষিকতা পর্যন্ত। আইনস্টাইন ইথারের ধারণাই অপসারণ করে দেন। সে মহান আবিষ্কার আমাদের আজকের আলোচ্য বিষয় নয়। তবে একটি বিষয় মাথায় রাখতে হবে। আপেক্ষিকতা তত্ত্ব ব্যাপক তাৎপর্যপূর্ণ ও অভিনব হলেও চিরায়ত পদার্থবিদ্যার স্পষ্টতা ও নিশ্চয়তাবাদকে বাতিল করে দেয়নি। এ কারণেই আমি ভূমিকায় বলেছি, কোয়ান্টাম তত্ত্বের চেয়ে বিশেষ আপেক্ষিকতায় চিন্তার মৌলিক পরিবর্তন প্রয়োজন হয়েছিল কম।

## বর্ণালী
কোয়ান্টাম বিপ্লবের প্রথম ইঙ্গিত মেলে ১৮৮৫ সালে। সেটা অবশ্য তখন বোঝা যায়নি। সুইশ স্কুলশিক্ষক বামারের খেয়ালি মনের গাণিতিক কাজ থেকে জিনিসটার সূচনা। তিনি হাইড্রোজেনের বর্ণালী নিয়ে ভাবছিলেন। উত্তপ্ত গ্যাসের আলোকে প্রিজমের ভেতর দিয়ে চালিয়ে দিলে রঙিন রেখাগুলো কীভাবে আলাদা হয় তা খেয়াল করছিলেন। আলোক তরঙ্গের আলাদা আলাদা রেখার ছিল আলাদা আলাদা কম্পাঙ্ক (স্পন্দনের হার)। সংখ্যাগুলোকে একটু নেড়েচেড়ে বামার দেখলেন, খুব সরল গাণিতিক সমীকরণ দিয়েই এ কম্পাঙ্কগুলোকে প্রকাশ করা যায় [দেখুন গাণিতিক পরিশিষ্ট ১]। সে সময় কাজটা ছিল এক কৌতুহলী মনের সাধারণ এক কাজের চেয়ে সামান্য বেশি গুরুত্বপূর্ণ।

পরবর্তীতে মানুষ পরমাণুর সমসাময়িক ধারণার আলোকে বামারের ফলাফল বুঝতে চাইলেন৷ ১৮৯৭ সালে এল জে জে থমসনের আবিষ্কার। তিনি দেখলেন, পরমাণুতে ছোট ছোট কণারা নেগেটিভ চার্জ বহন করে। পরে এ কণাদের নাম দেওয়া হয় ইলেকট্রন। ধরে নেওয়া যায়, পরমাণুজুড়ে ছড়িয়ে থাকা পজিটিভ চার্জ ইলেকট্রনকে ভারসাম্যে রাখে। একে বলা হয় কিশমিশ পুডিং মডেল। যেখানে ইলেকট্রন রাখত কিশমিশের ভুমিকা আর পজিটিভ চার্জধারী কণা পালন করত পুডিংয়ের ভূমিকা। তাহলে পুডিংয়ের মধ্যে ইলেকট্রন যতভাবে স্পন্দিত হবে, বর্ণালীর কম্পাঙ্কও সেরকম হবে। তবে বাস্তবে এই ধারণার সন্তোষজনক প্রয়োগ খুব কঠিন হয়ে দাঁড়াল। একটু পরেই আমরা দেখব, বামারের অদ্ভুত আবিষ্কারের প্রকৃত ব্যাখ্যা অন্য এক গুচ্ছ ধারণার মাধ্যমে পাওয়া যায়। তবে পরমাণুর প্রকৃতি নিয়ে কাজ তখনও জনপ্রিয় হয়ে ওঠেনি। আর তাই এ সমস্যাগুলো ব্যাপক পরিচিতি পায়নি।

## অতিবেগুনি বিপর্যয়
এর চেয়ে অনেক বড় ও চ্যালেঞ্জিং আরেকটি সমস্যা ছিল। ১৯০০ সালে লর্ড র‍্যালে সমস্যাটা প্রথম নিজরে আনেন। এটাই পরে অতিবেগুনি বিপর্যয় নামে পরিচিতি পায়। সনস্যাটার দেখা মেলে ঊনবিংশ শতকের আরেকটি মহান আবিষ্কার প্রয়োগ করতে গিয়ে। সে জিনিসটা হলো পরিসংখ্যানিক গতিবিদ্যা। বিজ্ঞানীরা খুব জটিল সিস্টেমের আচরণ বোঝার চেষ্টা করছিলেন। এমন সিস্ট যার বিস্তারিত গতির নানান ধরন থাকতে পারে। খুব আলাদা আলাদা অণু দিয়ে গঠিত গ্যাস এমন এক সিস্টেমের উদাহরণ। যেখানে প্রতিটি অণুর আছে আলাদা আলাদা গতি। আরেকটি উদাহরণ হলো বিকিরণজাত* [radiative] শক্তি। এটা গঠিত হতে পারে বহু আলাদা কম্পাঙ্ক দিয়ে। এমন জটিল সিস্টেমে কী ঘটে চলছে তার হিসাব রাখা প্রায় অসম্ভব একটি কাজ। এরপরেও খুব গুরুত্বপূর্ণ কিছু দিক জেনে নেওয়া যায়। এর কারণ হলো, গতির অনেকগুলো আলাদা আলাদা উপাদান জড় হয়েই তো সামগ্রিক আচরণের বহিঃপ্রকাশ ঘটে। গতির অনেকগুলো সম্ভাব্য অবস্থার মধ্যে সবচেয়ে বেশি সম্ভাব্যটাই ঘটে। এই সর্বোচ্চ সম্ভাব্যতার ভিত্তিতেই ক্লার্ক ম্যাক্সওয়েল ও লুডউইগ বোলজম্যান দেখান, জটিল সিস্টেমের সার্বিক আচরণের সামগ্রিক একটি বৈশিষ্ট্য হিসাব করে বের করা যায়। এই যেমন নির্দিষ্ট আয়তন ও তাপমাত্রায় একটি গ্যাসের চাপ।

র‍্যালে এবার পরিসংখ্যানিক পদার্থবিদ্যার এ কৌশল কাজে লাগালেন ব্ল্যাকবডি বা কৃষ্ণবস্তুর বিকিরণের সমস্যা সমাধানের জন্য। বুঝতে চাইলেন আলাদা আলাদা কম্পাঙ্কে শক্তি কীভাবে বণ্টিত হয়। ব্ল্যাকবডি এমন এক জিনিস যা এর ওপর আপতিত সব বিকিরণ শোষ করে নেয়। আবার পরে এর পুরোটা নির্গত করে দেয়। ব্ল্যাকবডির সাথে বিকিরণের বর্ণালী নিয়ে প্রশ্ন তোলাকে অদ্ভুত মনে হতে পারে। তবে বাস্তবে কিন্তু অনেকটা ব্ল্যাকবডির মতো জিনিসের দেখা পাওয়া যায়। ফলে বিষয়টা কেবলই তাত্ত্বিক কিছু নয়। একে বাস্তবেও পরীক্ষা করে দেখা যায়। এই যেমন, বিশেষভাবে নির্মিত একটি ওভেনের ভেতরের বিকিরণ পর্যবেক্ষণ করা যায়। আরেকটি জিনিস ব্যাপারটাকে আরও সহজ করে তোলে। জানা হয়ে গিয়েছিল, বিকিরণ নির্ভর করবে শুধুই তাপমাত্রার ওপর। বস্তুর বাকিসব বৈশিষ্ট্য এক্ষেত্রে অপ্রাসঙ্গিক।

র‍্যালে দেখালেন, পরিসংখ্যানিক পদার্থবিদ্যার সুপরীক্ষিত ধারণাগুলো ভয়াবহ ফল দিচ্ছে। একে তো তাত্ত্বিক হিসাব মেলে না পরিমাপের সাথে। তারওপর পাওয়া যায় অর্থহীন এক ফল। তত্ত্ব বলছে, সর্বোচ্চ কম্পাঙ্কে পাওয়া যাবে অসীম পরিমাণ শক্তি। এ বিব্রতকর ফলকেই পরে নাম দেওয়া হয় অতিবেগুনি বিপর্যয়*[*আরেকটু বিস্তারিত জানতে পড়ুন শূন্যের ভৌত বৈশিষ্ট্য,  জিরো: দ্যা বায়োগ্রাফি অব অ্যা ডাঞ্জারাস আইডিয়া। borrow some text ]। এ ফলের ভয়াবহরকম বৈশিষ্ট্য পরিস্কার। অতিবেগুনি হলো খুব উচ্চ কম্পাঙ্কের ও শক্তির আলো। বিপর্যয়ের কারণ হলো পরিসংখ্যানিক পদার্থবিদ্যা বলছে, বিকিরণের প্রত্যেকটি আলাদা তরঙ্গের থাকবে নির্দিষ্ট পরিমাণ শক্তি। এ শক্তির মান নির্ভর করবে শুধু তাপমাত্রার ওপর। কম্পাঙ্ক যত বেশি হবে, তত বেশি হবে স্পন্দনের ধরনের সংখ্যা। এভাবে হতে হতে সবচেয়ে বেশি কম্পাঙ্কে অসীম পরিমাণ শক্তি এসে জমা হয়। চিরায়ত পদার্থবিদ্যার সুন্দর প্রাসাদে বিশ্রী দাগ লেগে গেল। না শুধু দাগ নয়, যেন ধসেই গেল প্রাসাদখানি।

এক বছরের মাথায়ই ম্যাক্স প্ল্যাঙ্ক এ সমস্যার দারুণ এক সমাধান বের করলেন। সেসময় তিনি পদার্থবিদ্যার অধ্যাপনা করছেন। তিনি তাঁর ছেলেকে বললেন, তিনি নিউটনের আবিষ্কারের সমপর্যায়ের এক আবিষ্কার করে ফেলেছেন। শুনে হয়তো মনে হবে গালভরা এক দাবি। তিনি ঠিকই বলেছিলেন।

চিরায়ত পদার্থবিদ্যা বলে, বিকিরণ ব্ল্যাকবডিতে আপতিত ও নির্গত হয় অবিচ্ছিন্নভাবে। অনেকটা স্পঞ্জ থেকে পানি চুইয়ে পড়ার মতো। চিরায়ত পদার্থবিদ্যার মসৃণভাবে পরিবর্তনশীল জগতে অন্য কোনোকিছুকেই স্বাভাবিক মনে হচ্ছিল না। কিন্তু তবুও বিপরীত মত নিয়ে হাজির হলেন। বললেন, বিকিরণ অবিচ্ছিন্নভাবে নির্গত হয়। বরং সময় সময় নির্দিষ্ট সাইজের শক্তির প্যাকেট বা গুচ্ছ আকারে নির্গত হয়। তিনি বললেন, এমন একটি কোয়ান্টার (প্যাকেটগুলোর পরবর্তী নাম) শক্তির পরিমাণ হবে এর বিকিরণের কম্পাঙ্কের সমানুপাতিক*। দেখা গেল, এ সমানুপাতিক ধ্রুবকটি প্রকৃতির একটি সার্বজনীন ধ্রুবক। এখন একে আমরা বলি প্ল্যাঙ্কের ধ্রুবক ( প্রতীক h)। আমাদের দৈনন্দিন অভিজ্ঞতার তুলনায় এ ধ্রুবকের মান অত্যন্ত ক্ষুদ্র। আর এ কারণেই ধাপে ধাপে সংঘটিত বিকিরণের এ আচরণ আগে আঁচ করা যায়নি। অনেকগুলো বিন্দু পাশাপাশি থাকলে তাকে দেখে তো রেখা বলেই মনে হয়।

প্ল্যাঙ্কের নিতজন প্রস্তাবনা থেকে শুরুতেই বোঝা গেল, কেবল প্রচণ্ড শক্তির একটি কোয়ান্টাই উচ্চকম্পাঙ্কের বিকিরণ নির্গত বা শোষণ করতে পারে। এরা নির্গত হতে উচ্চশক্তির প্রয়োজনের মানে হলো চিরায়ত পদার্থবিদ্যার প্রত্যাশার তুলনায় এদেরকে অনেক কম পাওয়া যাবে। উচ্চকম্পাঙ্কের নতুন এ ব্যাখ্যা অতিবেগুনি বিপর্যয়ের সমাধান করে দিল। শুধু কি তাই? পাওয়া গেল একটি সূত্রো, যার সাথে বাস্তব ফলাফল মিলে অসম্ভব নিখুঁতভাবে।

প্ল্যাঙ্ক আসলেই বিরাট তাৎপর্যপূর্ণ এক কাজে হাত দিয়েছিলেন। তবে কাজের আসল গুরুত্বটা তিনি বা অন্য কেউই নিশ্চিত করে বুঝতে পারেনি। কোয়ান্টার ধারণা আসলে ঠিক কতটা গুরুত্বপূর্ণ? এটা কি বিকিরণের স্থায়ী কোনো বৈশিষ্ট্য? নাকি ব্ল্যাকবডির বিকিরণের বিশেষ কোনো ধর্ম? ট্যাপ থেকে  গড়িয়ে পড়া জলের ফোঁটাও জলীয় কোয়ান্টার ধারা তৈরি করে। কিন্তু বেসিনের পানিতে পড়ে অন্য পানির সাথে মিশে গিয়ে তারাও নিজস্ব পরিচয় হারিয়ে ফেলে।


## আলোকতড়িৎ ক্রিয়া
পরের অগ্রগতি ধরা দেয় একজন তরুণের হাতে। তাঁর হাতে তখন অফুরন্ত সময়। কাজ করছিলেন বার্নের প্যাটেন্ট অফিসের তৃতীয় শ্রেণির একজন পরীক্ষক হিসেবে। নাম অ্যালবার্ট আইনস্টাইন। ১৯০৫ সালটা তাঁর কাছে এক অলৌকিক বছর। এক বছরের মধ্যেই করে ফেলেন তিন তিনটা মৌলিক আবিষ্কার। এগুলোরই একটি কোয়ান্টাম তত্ত্বের পরবর্তী অগ্রগতির পথ খুলে দেয়। আলোকতড়িৎ ক্রিয়া নিয়ে কাজ করতে গিয়ে তিনি কিছু হতবুদ্ধিকর জিনিসের মুখোমুখি হন। এ ঘটনায় একটি আলোকরশ্মি ধাতব পদার্থ থেকে ইলেকট্রন বের করে আনে। ধাতুর মধ্যে থাকে ইলেকট্রন, যারা নিজস্ব অঞ্চলে চলাচল করতে থাকে (এদের প্রবাহের কারণেই বিদ্যুৎ তৈরি হয়।) তবে ধাতু থেকে বেরিয়ে আসার শক্তি ইলেকট্রনের নেই। আলোকতড়িৎ ক্রিয়ার ফলাফল মোটেও অভিনব ছিল না। বিকিরণের মাধ্যমে ধাতুতে আবদ্ধ ইলেকট্রনের মধ্যে শক্তি সঞ্চারিত হয়। এ শক্তি যথেষ্ট হলে ইলেকট্রন একে ধরে রাখা বলকে বৃদ্ধাঙ্গুলি দেখিয়ে মুক্ত হয়ে বাইরে চলে আসতে পারে। চিরায়ত চিন্তা পদ্ধতিতে হয়তো বলা হবে, ইলেকট্রনরা আলোর অধিক উপস্থিতিতে উত্তেজিত হয়েছে। আর কেউ কেউ যথেষ্ট উত্তেজিত হয়ে মুক্ত হয়ে বেরিয়ে এসেছে। এভাবে ভাবলে ইলেকট্রনের মুক্ত হওয়ার হার নির্ভর করবে আলোক রশ্মির তীব্রতার ওপর। কারণ তীব্রতা থেকেই আলোর শক্তির পরিমাণ পাওয়া যায়। আপতিত আলোর কম্পাঙ্কের কোনো ভূমিকা থাকবে না। কিন্তু পরীক্ষায় দেখা গেল পুরো উল্টো চিত্র। নির্দিষ্ট একটি কম্পাঙ্কের নীচে কোনো ইলেকট্রন বের হচ্ছে না। সে আলোর তীব্রতা যাই হোক না কেন। আর সে কম্পাঙ্কের বেশি দুর্বল বা অল্প তীব্রতার আলোও ইলেকট্রন মুক্ত করে আনতে পারে।

আইনস্টাইন দেখলেন, আলোকে অবিরাম প্রবাহিত কোয়ান্টার ধারা ধরে নিলে অদ্ভুত এ আচরণ সহজেই ব্যাখ্যা করা যায়। কোয়ান্টার সাথে সংঘর্ষে ইলেকট্রন মুক্ত হবে এবং সব শক্তি ত্যাগ করবে। প্ল্যাঙ্কের মতে সে কোয়ান্টার শক্তি কম্পাঙ্কের সরাসরি সমানুপাতিক। কম্পাঙ্ক বেশি ছোট হলে ইলেকট্রন সংঘর্ষের সময় যথেষ্ট শক্তি পাবে না। মুক্তও হবে না। অন্যদিকে কম্পাঙ্ক একটি নির্দিষ্ট মানের বেশি হলে ইলেকট্রন বের হয়ে যাওয়ার জন্য যথেষ্ট শক্তির যোগান পাবে। আলোকরশ্মির তীব্রতা থেকে শুধু বোঝা যায়, এতে কতগুলো কোয়ান্টা আছে। ফলে এটা দ্বারা বোঝাবে কতগুলো ইলেকট্রন সংঘর্ষ করেছে ও বের হয়ে গেছে। তীব্রতা বাড়ালেই একটিমাত্র সংঘর্ষের শক্তি বাড়বে না। আলোর কোয়ান্টার (পরবর্তী নাম ফোটন) অস্তিত্ব স্বীকার করে নিলে আলোকতড়িৎ ক্রিয়ার রহস্য সমাধান হয়ে যায়। তরুণ আইনস্টাইন অসাধারণ এক আবিষ্কার করেছেন। সত্যি বলতে, তিনি নোবেল পুরস্কারও পেয়েছেন এ অবদানের জন্যই। ১৯০৫ সালেই তিনি আরও দুটি মহান আবিষ্কার করেছিলেন। একটি বিশেষ আপেক্ষিকতা। অপরটি হলো অণুর অস্তিত্বের প্রমাণ। সুইডিশ একাডেমি (নোবেল কতৃপক্ষ) মনে করেছে, এ দুটি আবিষ্কার খুব বেশি অনুমাননির্ভর।

আলোকতড়িৎ ক্রিয়ার কোয়ান্টাম বিশ্লেষণ পদার্থবিদ্যার এক বিশাল বিজয়। তবুও মনে হয়, এর জন্য চড়া মূল্য দিতে হয়েছে। দেখা দিল বিশাল এক সঙ্কট। ঊনবিংশ শতকের মহান মহান আবিষ্কারগুলোর কী হবে, যেখানে আলোকে তরঙ্গ ধরে নিয়ে সব দারুণ অগ্রগতি হয়েছে? দুই ধারণার সমন্বয় কীভাবে হবে? তরঙ্গ তো ছড়িয়ে পড়ে, দোল খায়। অন্যদিকে কোয়ান্টাম হলো কণার মতো, যেন ক্ষুদ্র এক বুলেট। দুটোই কীভাবে সত্য হয়? দীর্ঘ সময় ধরে পদার্থবিদরা আলোর তরঙ্গ/কণা নিয়ে বিড়ম্বনায় ছিলেন। ইয়ং ও ম্যাক্সওয়েল বা প্ল্যাঙ্ক ও আইনস্টাইনের আবিষ্কারকে অস্বীকার কেউ করতে পারেনি। বাস্তব অবস্থা আসলে কী বোঝার চেষ্টা করে গেছেন। কিন্তু কোনো কিনারা খুঁজে পাওয়া যায়নি। কেউ কেউ কাপুরুষের মতো না দেখার ভান করে গেছেন। তবে শেষপর্যন্ত গল্পের একটি সুন্দর পরিসমাপ্তি ঘটেছে।

## নিউক্লীয় পরমাণু
ঠিক যেভাবে প্ল্যাঙ্ক অতিবেগুনি বিপর্যয় থেকে রক্ষা করেছেন, সেভাবেই এবারও এগিয়ে এলেন একজন। সাহসী ও মৌলিক এক অনুমানের মাধ্যমে
ব্যর্থতার সমুদ্রে সফলতার পতাকা উড়িয়ে দিলেন পতপত করে। এবারের ত্রাণকর্তা তরুণ ড্যানিশ বিজ্ঞানী নিলস বোর। কাজ করতেন ম্যানচেস্টারের রাদারফোর্ডে। ১৯১৩ সালে বোর বৈপ্লবিক এক প্রস্তাব তুলে ধরেন। এর আগে প্ল্যাঙ্ক চিরায়ত পদার্থবিদ্যা মসৃণ প্রক্রিয়াকে প্রতিস্থাপন করেছিলেন। ব্ল্যাকবডি থেকে ক্রমাগত শক্তি বেরিয়ে আসার বদলে বললেন, শক্তি নির্গত বা শোষিত হয় কোয়ান্টা আকারে থেমে থেমে। আগের ধারণা অনুসারে শক্তির বিনিময় ঘটতে পারে যেকোনো পরিমাণে। কিন্তু নতুন ব্যাখ্যা অনুসারে, শক্তি পরিমাণ শুধু নির্দিষ্ট কিছু মান হতে পারে (১, ২, ৩… প্যাকেট ইত্যাদি)। গণিতের ভাষায় বললে, বললে হবে, অবিচ্ছিন্ন মানের জায়গায় এসেছে বিচ্ছিন্ন মান* [*বিচ্ছিন ও অবিচ্ছিন্ন চলক সম্পর্কে একটুখানি না জানলেই নয়। গণিত ও পরিসংখ্যান থেকে মূলত ধারণাটির উৎপত্তি৷ যে চলকের মানে নির্দিষ্ট দুটি সংখ্যার মাঝে অন্য সংখ্যা হতে পারে না সেটি বিচ্ছিন্ন চলক। যেমন স্বাভাবিক সংখ্যারা হলো ১, ২, ৩, ... ইত্যাদি অসীম পর্যন্ত৷ ১ ও ২ এর মাঝে কেউ নেই। এমন রাশিদের সেট বিচ্ছিন্ন। আবার বাস্তব সংখ্যার কথা ধরুন। ১ ও ২ এর মাঝে আছে অসীমসংখ্যক সংখ্যা৷ শুধু কি তাই! ১.১ ও ১.২ এর মাঝেই আছে অসীম সংখ্যা৷ একই কথা চলে ১.১১ ও ১.১২ এর জন্য। আসলে যেকোনো দুই সংখ্যার মাঝেই অসীম সংখ্যা আছে৷ বাস্তব সংখ্যারা তাই অবিচ্ছিন্ন। এদের মাঝে নেই কোনো গ্যাপ বা ফাঁকা জায়গা-অনুবাদক] বোর খেয়াল করলেন, নতুন ধরেনর পদার্থবিজ্ঞানে ক্রমশ এ প্রবণতা তৈরিি হচ্ছে। প্ল্যাঙ্ক যে নীতি কাজে লাগিয়েছেন বিকিরণের ক্ষেত্রে, বোর সে নইটি প্রয়োগ করলেন পরমাণুর ক্ষেত্রে। চিরায়ত পদার্থবিদ ভাববেন, নিউক্লিয়াসকে প্রদক্ষিণ করা ইলেকট্রনের কক্ষপথ যেকোনো জায়গায় হতে পারে। বোর বললেন, কক্ষপথের অবস্থান অবিচ্ছিন্নভাবে ইচ্ছেমতো যেকোথাও হতে পারে না। কক্ষপথ থাকতে পারে কেবল নির্দিষ্ট কিছু জায়গায়। যার ব্যাসার্ধ গণনা করা যাবে (১ম, ২য়, ৩য় ইত্যাদি)। এ ব্যাসার্ধগুলো বের করারও সুনির্দিষ্ট পদ্ধতিও প্রস্তাব করেন তিনি। ব্যবহার করলেন প্ল্যাঙ্কের ধ্রুবক (h)। (প্রস্তাবনাটার সাথে কৌণিক ভরবেগের সম্পর্ক আছে। রাশিটি ইলেকট্রনের ঘূর্ণন গতির হিসাব প্রদান করে। দুটি রাশির একক একই।)

এসব প্রস্তাবনা থেকে দুটি ফল পাওয়া গেল। এর একটি হলো পরমাণুর বহুআকাঙ্খিত স্থিতিশীলতা। ইলেকট্রন একবার সর্বনিম্ন অনুমোদিত ব্যাসার্ধে (সর্বনিম্ন শক্তির অবস্থাও) পৌঁছে গেলে এর যাওয়ার আর কোনো জায়গা থাকে না। ফলে এটি আর কোনো শক্তি হারাতে পারে না। কোনাটি এখানে এসেছেই উচ্চতর ব্যাসার্ধের কক্ষপথ থেকে শক্তি হারিয়ে। বোর ধরে নিলেন, এটা ঘটলে (নিম্ন কক্ষপথে আসলে) বাড়তি শক্তিটুকু একটিমাত্র ফোটন আকারে বিকিরিত হয়ে যায়। যোগফল বের করে দেখা গেল, এই ভাবনা থেকেই সরাসরি পাওয়া যাচ্ছে বোরের সাহসী অনুমানের দ্বিতীয় ফলাফল। আর সেটিই হলো বর্ণালী রেখার বামার সূত্র। ত্রিশ বছর পরে এ তত্ত্বই ব্যাখ্যাতীত এক অদ্ভুত জিনিস থেজে হয়ে গেল পরমাণুর নতুন তত্ত্বের এক অনিবার্য অংশ। বর্ণালী রেখার তীক্ষ্মতা ব্যাখ্যা করা হলো বিচ্ছিন্নতার বহিঃপ্রকাশ হিসেবে। এ অবিচ্ছিন্নতা কোয়ান্টাম চিন্তার প্রতীক হয়ে উঠতে শুরু করল। চিরায়ত পদার্থবিদ্যার ক্রমাগত সর্পিল গতির বদলে এল তীক্ষ্ম বিচ্ছিন্ন লাফ। যেখানে ইলেকট্রন কোনো এক অনুমোদিত কক্ষপথ থেকে নিম্নতর অনুমোদিত কক্ষপথে চলে যায়।

বোর পরমাণু ছিল এক বিশাল সাফল্য। কিন্তু তাও অনেক দিক থেকেই এটা পুরনো চিরায়ত চিন্তাধারারই রূপ বদল। বোরের অভিনব কাজটা মূলত ছিল এক ধরনের মেরামত। চিরায়ত পদার্থবিদ্যার প্রাসাদে জোড়াতালি। এ ধারণাগুলোকে আরও প্রসারিত করা ক্রমেই দুরূহ হয়ে ওঠল। পাওয়া যেতে থাকল নানা অসঙ্গতি। এ ‘পুরাতন কোয়ান্টাম তত্ত্ব’ নিউটন ও ম্যাক্সওয়েলের চিরায়ত ধারণার সাথে প্ল্যাঙ্ক ও আইনস্টাইনের কোয়ান্টাম দর্শনের সমন্বয় হচ্ছিল না। কোয়ান্টাম পদার্থবিদ্যার ভিত্তি তৈরিতে বোরের কাজ গুরুত্বপূর্ণ এক পদক্ষেপ। তবে সেটি পূর্ণাঙ্গ ও সম্পূর্ণ সুসঙ্গত ‘নতুন কোয়ান্টাম তত্ত্বের’ ক্ষেত্রে শুধুই একটি পথনির্দেশক হিসেবেই কাজ করেছে। তবে নতুন তত্ত্বটা প্রস্তুত হওয়ার আগে আরও একটি ঘটনা গুরুত্বপূর্ণ ভূমিকা রেখেছে। এর মাধ্যমেই কোয়ান্টাম চিন্তাভাবনার সাথে খাপ খাইয়ে নেওয়ার গুরুত্ব পরিস্কার হয়ে যায়।

## কম্পটন বিচ্ছুরণ
 ১৯২৩ সালে মার্কিন পদার্থবিদ আর্থার কম্পটন বস্তুর আঘাতে সৃষ্ট এক্স-রে (উচ্চ কম্পাঙ্কের তড়িচ্চুম্বকীয় বিকিরণ) বিচ্ছুরণ নিয়ে কাজ করছিলেন। তিনি খেয়াল করে দেখলেন, বিচ্ছুরিত বিকিরণের কম্পাঙ্ক বদলে যাচ্ছে। তরঙ্গের দৃষ্টিকোণ থেকে দেখলে এর কোনো ব্যাখ্যা নেই। এক্স রশ্মিকে তরঙ্গ ধরে নিলে এর অর্থ হবে, বিচ্ছুরণ ঘটছে আপতিত তরঙ্গ থেকে পরমাণুর ইলেকট্রনের শক্তি শোষণ ও নির্গমনের কারণে। আর ব্যাপারটা ঘটতে কম্পাঙ্কের কোনো পরিবর্তন হবে না। তবে ফোটন দৃষ্টিকোণ থেকে ভাবলে ব্যাখ্যাটা খুব সহজ। ইলেকট্রন ও ফোটন কণায়-কণায় সংঘর্ষ হবে। যার ফলে ফোটনের কিছু শক্তি ক্ষয় হয়ে ইলেকট্রনে জমা হবে। প্ল্যাঙ্ক বলেছেন, শক্তির পরিবর্তন মানে কম্পাঙ্কের পরিবর্তন। কম্পটন তাঁর পর্যবেক্ষণের একটি পরিমাণমূগত ব্যাখ্যা দিতে সক্ষম হলেন। এরই মাধ্যমে তড়িচ্চুম্বকীয় বিকিরণের কণাসদৃশ আচরণ সম্পর্কে এযাবতকালের সবচেয়ে বোধগম্য ব্যাখ্যা পাওয়া গেল।

এসব আবিষ্কার থেকে সৃষ্ট ধাঁধাঁগুলো অবশ্য বেশিদিন অমীমাংসিত থাকেনি। কম্পটনের আবিষ্কারের দুই বছরের মধ্যেই এ বিষয়ে বড় ও স্থায়ী তাত্ত্বিক অগ্রগতি হলো। উদিত হতে শুরু করল নতুন কোয়ান্টাম তত্ত্ব।
