# ভূমিকা {.unnumbered}

১৯২০-এর দশকের মাঝামাঝি সময়ে আধুনিক কোয়ান্টাম তত্ত্ব আবিষ্কৃত হয়। আইজ্যাক নিউটন পরবর্তী সময়ে ভৌত পৃথিবী সম্পর্কে আমাদের চিন্তাজগতে সবচেয়ে বড় পরিবর্তন আনে তত্ত্বটি। যে জগতটার আচরণ আগে মনে হত পরিস্কার ও নিশ্চিত, অতিপারমাণবিক ভিত্তিমূলে দেখা গেলে সে আচরণ করছে মেঘাচ্ছন্ন ও এলোমেলো উপায়ে। এ বৈপ্লবিক পরিবর্তন ছাড়িয়ে গেল আপেক্ষিকতার বিশেষ ও সার্বিক তত্ত্বের আকর্ষণকেও। এ তত্ত্বদুটিকে পুরনো (চিরায়ত) তত্ত্বের মৃদু রূপপরিবর্তন বলেই মনে হলো।

আপেক্ষিকতার জনক আইনস্টাইন কোয়ান্টাম তত্ত্বকে গ্রহণ করতে পারেননি। জীবনের শেষ দিন পর্যন্ত করে গেছেন নিষ্ঠুর বিরোধিতা [^1] । কিন্তু কোয়ান্টাম তত্ত্বকে বিংশ শতকের অন্যতম অসাধারণ বুদ্ধিবৃত্তিক অর্জন বললে একটুও বাড়িয়ে বলা হবে না। ভৌত প্রক্রিয়াগুলোর ব্যাখ্যায় সত্যিকারের বিপ্লব নিয়ে আসে তত্ত্বটি।

কিন্তু কোয়ান্টাম তত্ত্বের পূর্ণাঙ্গ আনন্দ কেন শুধু তাত্ত্বিক পদার্থবিদরাই পাবেন? হ্যাঁ, তত্ত্বটাকে পুরোপুরি বুঝতে চাইলে এর নিজস্ব ভাষা ও গণিত জানতে হবে। তবুও অনেকগুলো ধারণাই সাধারণ পাঠকের কাছে বোধগম্য করে তোলা যায়। তবে পাঠককেও সেজন্য একটু কষ্ট তো স্বীকার করতেই হবে। যত্নের সাথে ইতিহাসের গুরুত্বপূর্ণ গল্পগুলোতফ চখ বুলিয়ে যেতে হবে। এ ধরনের পাঠকের কথা মাথায় রেখেই বইটি লেখা। বইটির মূল অংশে কোনো গাণিতিক সমীকরণ নেই। ছোট্ট একটি পরিশিষ্টে সরল কিছু গাণিতিক ধারণা তুলে ধরেছি। যারা আরেকটু বেশি স্বাদ পেতে চান তারা এখান থেকে উপকৃত হবেন (পরিশিষ্টের সংশ্লিষ্ট অংশের রেফারেন্স বইয়ের মূল বইয়ে উল্লেখ করা আছে)।

আবিষ্কারের পরবর্তী প্রায় ১০০ বছর ধরে কোয়ান্টাম তত্ত্ব অসাধারণ সফলতা বয়ে এনেছে। বর্তমানে তত্ত্বটাকে আত্মবিশ্বাস নিয়ে ব্যবহার করা যায়। কোয়ার্ক ও গ্লুয়নের (পরমাণুর কেন্দ্রের মৌলিক উপাদান হিসেবে আপাতত বিবেচিত কণা) মতো কণাদের আচরণ ব্যাখ্যায় দারুণ সফল এ তত্ত্ব। অথচ এ কথাগুলোর আকার পরমাণুর তুলনায় ১০ কোটি গুণ ছোট। তাও কোয়ান্টাম তত্ত্বের জনকদের গবেষণা শুরু হয়েছিল পরমাণু নিয়ে কাজ করতে গিয়ে। তবুও একটি প্যারাডক্স [^2]  থেকেই যায়।

বইটির শুরুতে একটি উক্তি আছে দেখবেন। এতে অনেকখানিই বাড়িয়ে বলা হয়েছে। দ্বিতীয় প্রজন্মের অন্যতম মহান কোয়ান্টাম পদার্থবিদ রিচার্ড ফাইনম্যান বিভিন্ন বক্তৃতায় এ সুরেই কথা বলতেন। তবে কথাটা একটু বাড়াবাড়ি হলেও একদম ফেলে দেওয়ার মতো নয়। আমরা জানি, তত্ত্বটার যোগফলগুলো কীভাবে করতে হয়। তবুও তত্ত্বটাকে যতটা বোঝা উচিত ঠিক ততটা পুরোপুরি আমরা বুঝি না। একটু পরেই আমরা দেখব, তত্ত্বের ব্যাখ্যার বিভিন্ন দিক নিয়ে সমস্যা এখনও আছে। এগুলোর সমধানের জন্য ভৌত জ্ঞান তো লাগবেই, লাগবে অধিবিদ্যাগত [^3] উপলব্ধিও।

তরুণ বয়সে পল ডিরাকের কাছ থেকে কোয়ান্টাম তত্ত্ব শেখার সৌভাগ্য হয়েছিল আমার। ক্যামব্রিজে তিনি তখন বিখ্যাত লেকচার দিচ্ছিলেন। কোয়ান্টাম তত্ত্বের মৌলিক বষয় নি‌‌‌য়ে তিনি লিখেছিলেন দ্য পিন্সিপিলস অব কোয়ান্টাম মেকানিকস বই। বিংশ শতকের অন্যতম উঁচু মানের বিজ্ঞান সাহিত্য এ বই। লেকচারের সাথে আবার বইটির দারুণ মিল ছিল। ডিরাক ছিলেন আমার দেখা সেরা তাত্ত্বিক পদার্থবিদ। এছাড়াও তাঁর আচরণের অকৃত্রিমতা ও বিনয় (কোয়ান্টাম গতিবিদ্যার মৌলিক ভিত্তিতে তাঁর নিজের অসামান্য আবিষ্কার তিনি অনেকটাই এড়িয়ে গেছেন।) তাঁকে অনুসরণীয ব্যক্তিত্বে পরিণত করে। এ এক ধরনের বৈজ্ঞানিক সাধু। আমি সশ্রদ্ধচিত্তে বইটা তাঁকে উৎসর্গ করছি।

[^1]: যদিও তাঁর নোবেলটা পাওয়া কোয়ান্টাম তত্ত্বেই। আলোকতড়িৎ ক্রিয়া ব্যাখ্যায় ১৯২১ সালে নোবেল পুরস্কার পান তিনি--অনুবাদক]
[^2]: অসীম সমীকরণ বই
[^3]:  বাস্তবতা ও অস্তিত্ব  বিষয়ক জ্ঞান। অধিবিদ্যায় মানুষের অস্তিত্ত্বের স্বরূপ ও উদ্দেশ্য নিয়ে আলোচনা করা হয়।
